docs: Update links to reflect core cardano code migration to intersect
input-output-hk/sanchonet pull request #119
Opened 2023-12-22 16:15 UTC by Ryun1

2023-12-23 14:05 UTC, disassembler commented on docs/tutorials/start-a-node.mdx
> +* The latest version for SanchoNet is **8.3.0-pre**. [See releases](https://github.com/IntersectMBO/cardano-node/releases)
This should be 8.7.2

2024-01-02 15:00 UTC, Ryun1 commented on docs/roles/dev.mdx
> +1. Download the node [v.8.2.1-pre](https://github.com/IntersectMBO/cardano-node/releases/tag/8.2.1-pre)
```suggestion
1. Download the node [v.8.7.2](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.2)
```

2024-01-02 15:00 UTC, Ryun1 commented on docs/tutorials/start-a-node.mdx
> +* The latest version for SanchoNet is **8.3.0-pre**. [See releases](https://github.com/IntersectMBO/cardano-node/releases)
```suggestion
* The latest version for SanchoNet is **8.7.2**. [See releases](https://github.com/IntersectMBO/cardano-node/releases)
```

2024-01-02 15:01 UTC, Ryun1 commented on docs/tutorials/start-a-node.mdx
> +* The latest version for SanchoNet is **8.3.0-pre**. [See releases](https://github.com/IntersectMBO/cardano-node/releases)
done!

2024-01-11 16:37 UTC, disassembler requested changes

2024-01-11 16:37 UTC, disassembler commented on docs/roles/dev.mdx
> +1. Download the node [v.8.7.2](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.2)
8.7.3 now

2024-01-11 16:37 UTC, disassembler commented on docs/roles/drep.mdx
> +1. Download the node [v.8.7.2](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.2)
8.7.3 now

2024-01-11 16:37 UTC, disassembler commented on docs/tutorials/start-a-node.mdx
>  * The latest version for SanchoNet is **8.3.0-pre**. [See releases](https://github.com/input-output-hk/cardano-node/releases).
8.7.3 here

2024-01-11 16:40 UTC, Ryun1 commented on docs/roles/dev.mdx
> +1. Download the node [v.8.7.2](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.2)
```suggestion
1. Download the node [v.8.7.3](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.3)
```

2024-01-11 16:41 UTC, Ryun1 commented on docs/roles/drep.mdx
> +1. Download the node [v.8.7.2](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.2)
```suggestion
1. Download the node [v.8.7.3](https://github.com/IntersectMBO/cardano-node/releases/tag/8.7.3)
```

2024-01-11 16:41 UTC, Ryun1 commented on docs/tutorials/start-a-node.mdx
>  * The latest version for SanchoNet is **8.3.0-pre**. [See releases](https://github.com/input-output-hk/cardano-node/releases).
```suggestion
* The latest version for SanchoNet is **8.7.3**. [See releases](https://github.com/input-output-hk/cardano-node/releases).
```

2024-01-11 16:50 UTC, disassembler approved these changes

2024-01-11 17:06 UTC, disassembler approved these changes

2024-01-11 17:07 UTC, merged