index.tsx: minor edits
input-output-hk/sanchonet pull request #62
Opened 2023-08-18 07:30 UTC by olgahryniuk

2023-08-21 16:10 UTC, disassembler requested changes

2023-08-22 05:47 UTC, olgahryniuk commented on src/components/HomepageFeatures/index.tsx
> +        SanchoNet provides liquid democracy to get a high voter turnout. A DRep is
Tweaked

2023-08-31 03:47 UTC, disassembler approved these changes

2023-09-01 19:52 UTC, CarlosLopezDeLara approved these changes

2023-09-02 02:02 UTC, disassembler approved these changes

2023-09-02 02:02 UTC, merged